---

services:
  background:
    image: busybox
    command: sleep 50000
  hello:
    depends_on:
      - background
    image: busybox
    command: >-
      sh -c "echo 'proof' > /cache/proof
      && echo '${HELLO:-World}'"
      && echo '{"color": "lime", "subject":"demo", "status":"${HELLO:-World}"}' > /data/demo.badge
    volumes:
      - "./cache:/cache"
      - "./data:/data"
